name: pr-comment

on:
  workflow_run:
    workflows:
      - ci-pr
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2.22.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: pr.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ./diagram/pr_num.txt

      - name: Upload a picture
        uses: devicons/public-upload-to-imgur@v2.2.2
        id: imgur_step
        with:
          path: ./diagram/diagram.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}

      - name: Comment on the PR about the result
        uses: actions/github-script@v5
        env:
          IMG_URL: ${{ fromJSON(steps.imgur_step.outputs.imgur_urls)[0] }}
          PR_NUM: ${{ steps.pr_num_reader.outputs.content }}
        with:
          script: |
            const url = process.env.IMG_URL
            const pr = process.env.PR_NUM
            github.issues.createComment({
              issue_number: pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `![Image](${url})`
            })
