name: ci-pr

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.7'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install
        run: pip install -r requirements.txt

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Generate diagrams
        run: python diagram.py

      # see: https://github.community/t/pull-request-attribute-empty-in-workflow-run-event-object-for-pr-from-forked-repo/154682/3
      - name: Prepare upload artifact
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          mkdir images
          mv diagram.png images
          echo $PR_NUM > images/pr_num.txt

      # NOTE: Dependabot PRs will run with read-only permission.
      #       see: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
      #       Upload the image and PR number to the artifact, and use Secret to upload the image to imgur in the main branch job triggered by workflow_run.
      #       Then comment the image in the PR.
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: diagram
          path: images
